version: '3'

services:
  node:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm start
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:5-alpine
    restart: always
